### ISSUE TITLE
video tutorial

### ISSUE THREAD

**Issue by lamo-git** [asciidude/CSLMessageLogger#4]
can u make a youtube tutorial for this lol because im absolutely lost when i do npm install in the console i get these errors https://i.imgur.com/tpsgbXS.png and im sure im not the only one lost and tbh the vid would prob only be like 5 minutes long if u were to make it so yea could u pls n thx

**Comment by ThatKoffe** [comment]
hi @lamo-git 

i may not be the dev of this project - but you're not in the project directory, you're in the system32 dir.

try running: `git clone https://github.com/asciidude/CSLMessageLogger ml_bot && cd ml_bot` to install the project and going to it's respective directory.

after you'll need to run `npm i` to install the packages.

hope this helped you!

**Comment by asciidude** [comment]
I'll try making a video tutorial later today or tomorrow

**Comment by asciidude** [comment]
Hey, I can't make a video tutorial. I have no time, but if I ever get the time to I will and then I'll update the `README` with it
