### ISSUE TITLE
Doesnt log anything

### ISSUE THREAD

**Issue by Kavalll** [asciidude/CSLMessageLogger#5]
Cant get it to log anything even though everything is set up correctly without any edits to config or env, other than token input
is it broken or am i doing smt wrong?
https://i.imgur.com/F3oxhJk.png

**Comment by Kavalll** [comment]
https://i.imgur.com/Ufm6qwy.png 
got it to start logging but got an error now

**Comment by nullablepointer** [comment]
same error :/

**Comment by asciidude** [comment]
Show your config please, also make sure it is updated to the latest version. The latest version, at least I thought, had all these bugs fixed

**Comment by asciidude** [comment]
Closing now, please re-comment if you're still experiencing issues with CSLMessageLogger.
